# Site settings
title: AWSKRUG - 대학생 서포터즈 그룹
email: locutusss0166@gmail.com
description: |
  AWSKRUG 대학생 서포터즈 그룹
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pouu69.github.io" # the base hostname & protocol for your site

github_username: pouu69

timezone: Asia/Seoul

repository: pouu69/pouu69.github.io

permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

gems:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]

author: pouu69@gmail.com
asset_url: /assets
